mybatis:
  config-location: mybatis/mybatis-config.xml
  mapper-locations: mybatis.mapper/*.xml
  type-aliases-package: com.ncu.sysweb.entity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 2254655