spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://***:3306/ncu?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=true&autoReconnect=true
    username: root
    password: ***
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
